apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-iesu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-iesu
    app.kubernetes.io/part-of: test-app-398
  name: test-component-iesu
  namespace: build-templates-e2e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: maven-hello-world
      app.kubernetes.io/instance: test-component-iesu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maven-hello-world
        app.kubernetes.io/instance: test-component-iesu
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:e4d0661aa33a48bdaaa77da133e108ba
        name: maven-hello-world
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
status: {}
