apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-vdkj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-vdkj
    app.kubernetes.io/part-of: test-app-398
  name: test-component-vdkj
  namespace: build-templates-e2e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: test-component-vdkj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: test-component-vdkj
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:7487e23b719e42b09df2f323ed83f687
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
