apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-tlpx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-tlpx
    app.kubernetes.io/part-of: test-app-398
  name: test-component-tlpx
  namespace: build-templates-e2e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-tlpx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-tlpx
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:70a87882d1e147f4814634fd4c5787c2
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
