apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-yyby
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-yyby
    app.kubernetes.io/part-of: test-app-398
  name: test-component-yyby
  namespace: build-templates-e2e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: test-component-yyby
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: test-component-yyby
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:18919d39075c40f99be680db330f63b0
        name: fbc
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
