apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-emap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-emap
    app.kubernetes.io/part-of: test-app-398
  name: test-component-emap
  namespace: build-templates-e2e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-no-dockerfile
      app.kubernetes.io/instance: test-component-emap
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-no-dockerfile
        app.kubernetes.io/instance: test-component-emap
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:d422822db8704344aa6af5d12d68e856
        name: nodejs-no-dockerfile
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
status: {}
